### ISSUE TITLE
Blog template

### ISSUE THREAD

**Issue by abiyug** [amunategui/Feedback#6]
Hi Manuel,
I am a fan of your blog. Thanks for sharing some great tips.  I like the simplicity and feel of your blog and would like to emulate my blog after yours.  So here are few questions.
1. Are you using jekyll theme?
2. If so, which theme did you use?

Thanks,

Abiyu
Newly minted DS from JHU/Coursera

**Comment by amunategui** [comment]
Hi Abiyu, thanks for the feedback - the entire base was copied from : http://erjjones.github.io/blog/How-I-built-my-blog-in-one-day/

Hope that helps - great job on the DS!
amunategui@gmail.com
